### ISSUE TITLE
XYPlot failed to load a large data set

### ISSUE THREAD

**Issue by thinhly197** [uber/react-vis#949]
I'm using react-vis@1.10.8
I got the issue when try to load the XYPlot chart with 1827 bars. The code snippet is my implementation.
If I make the smaller copy of _**dataPoints**_, the code works well.
Please help to take a look. Thanks

`<FlexibleXYPlot
              animation
              height={600}
              onMouseLeave={this._mouseLeaveHandler}
              getX={d => d.point}
              getY={d => d.num}
            >
              {/* <VerticalGridLines /> */}
              {/* <HorizontalGridLines /> */}
              <XAxis title="point" /> */}
              <YAxis hideTicks hideLine />
              <VerticalBarSeries
                data={dataPoints}
                color="#1a2472"
                onNearestX={this._nearestXHandler}
              />
              <Crosshair
                itemsFormat={this._formatCrosshairItems}
                titleFormat={this._formatCrosshairTitle}
                values={crosshairValues}
              />
            </FlexibleXYPlot>`

> Uncaught TypeError: Cannot read property 'prototype' of undefined
>     at isSeriesChild (series-utils.js:36)
>     at series-utils.js:48
>     at Array.filter (<anonymous>)
>     at getSeriesChildren (series-utils.js:47)
>     at new XYPlot (xy-plot.js:146)
>     at constructClassInstance (react-dom.development.js:11448)
>     at updateClassComponent (react-dom.development.js:13145)
>     at beginWork (react-dom.development.js:13825)
>     at performUnitOfWork (react-dom.development.js:15864)
>     at workLoop (react-dom.development.js:15903)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:100)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
>     at invokeGuardedCallback (react-dom.development.js:187)
>     at replayUnitOfWork (react-dom.development.js:15311)
>     at renderRoot (react-dom.development.js:15963)
>     at performWorkOnRoot (react-dom.development.js:16561)
>     at performWork (react-dom.development.js:16483)
>     at performSyncWork (react-dom.development.js:16455)
>     at requestWork (react-dom.development.js:16355)
>     at scheduleWork$1 (react-dom.development.js:16219)
>     at Object.enqueueSetState (react-dom.development.js:11300)
>     at Connect../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:270)
>     at Connect.onStateChange (connectAdvanced.js:205)
>     at Object.dispatch (redux.js:221)
>     at dispatch (<anonymous>:1:38223)
>     at middleware.js:66
>     at dispatch (redux.js:563)
>     at utils.js:250
>     at proc.js:489
>     at exec (scheduler.js:19)
>     at flush (scheduler.js:60)
>     at asap (scheduler.js:33)
>     at runPutEffect (proc.js:486)
>     at runEffect (proc.js:435)
>     at next (proc.js:315)
>     at currCb (proc.js:388)
> isSeriesChild @ series-utils.js:36
> (anonymous) @ series-utils.js:48
> getSeriesChildren @ series-utils.js:47
> XYPlot @ xy-plot.js:146
> constructClassInstance @ react-dom.development.js:11448
> updateClassComponent @ react-dom.development.js:13145
> beginWork @ react-dom.development.js:13825
> performUnitOfWork @ react-dom.development.js:15864
> workLoop @ react-dom.development.js:15903
> callCallback @ react-dom.development.js:100
> invokeGuardedCallbackDev @ react-dom.development.js:138
> invokeGuardedCallback @ react-dom.development.js:187
> replayUnitOfWork @ react-dom.development.js:15311
> renderRoot @ react-dom.development.js:15963
> performWorkOnRoot @ react-dom.development.js:16561
> performWork @ react-dom.development.js:16483
> performSyncWork @ react-dom.development.js:16455
> requestWork @ react-dom.development.js:16355
> scheduleWork$1 @ react-dom.development.js:16219
> enqueueSetState @ react-dom.development.js:11300
> ./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:270
> onStateChange @ connectAdvanced.js:205
> dispatch @ redux.js:221
> dispatch @ VM345:1
> (anonymous) @ middleware.js:66
> dispatch @ redux.js:563
> (anonymous) @ utils.js:250
> (anonymous) @ proc.js:489
> exec @ scheduler.js:19
> flush @ scheduler.js:60
> asap @ scheduler.js:33
> runPutEffect @ proc.js:486
> runEffect @ proc.js:435
> next @ proc.js:315
> currCb @ proc.js:388
> Promise.then (async)
> resolvePromise @ proc.js:450
> runCallEffect @ proc.js:517
> runEffect @ proc.js:435
> next @ proc.js:315
> currCb @ proc.js:388
> (anonymous) @ proc.js:499
> exec @ scheduler.js:19
> flush @ scheduler.js:60
> asap @ scheduler.js:33
> (anonymous) @ channel.js:185
> emit @ channel.js:26
> (anonymous) @ middleware.js:67
> dispatch @ VM345:1
> onLoadAggregation @ index.js:53
> Table._this._viewGraph @ index.js:136
> onClick @ index.js:60
> callCallback @ react-dom.development.js:100
> invokeGuardedCallbackDev @ react-dom.development.js:138
> invokeGuardedCallback @ react-dom.development.js:187
> invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
> executeDispatch @ react-dom.development.js:461
> executeDispatchesInOrder @ react-dom.development.js:480
> executeDispatchesAndRelease @ react-dom.development.js:581
> executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
> forEachAccumulated @ react-dom.development.js:562
> runEventsInBatch @ react-dom.development.js:723
> runExtractedEventsInBatch @ react-dom.development.js:732
> handleTopLevel @ react-dom.development.js:4477
> batchedUpdates$1 @ react-dom.development.js:16660
> batchedUpdates @ react-dom.development.js:2131
> dispatchEvent @ react-dom.development.js:4556
> interactiveUpdates$1 @ react-dom.development.js:16715
> interactiveUpdates @ react-dom.development.js:2150
> dispatchInteractiveEvent @ react-dom.development.js:4533
> index.js:2178 The above error occurred in the <XYPlot> component:
>     in XYPlot (created by FlexibleXYPlot)
>     in div (created by FlexibleXYPlot)
>     in FlexibleXYPlot (at index.js:89)
>     in div (at index.js:88)
>     in div (created by TabPane)
>     in TabPane (at index.js:86)
>     in div (created by TabContent)
>     in TabContent (created by Tabs)
>     in div (created by Tabs)
>     in Tabs (created by Tabs)
>     in Tabs (at index.js:85)
>     in GraphView (at presenter.js:78)
>     in div (created by styled.div)
>     in styled.div (at presenter.js:77)
>     in div (created by styled.div)
>     in styled.div (at presenter.js:53)
>     in Route (at presenter.js:51)
>     in Switch (at presenter.js:49)
>     in MainContentsPresenter (created by Connect(MainContentsPresenter))
>     in Connect(MainContentsPresenter) (at presenter.js:14)
>     in div (created by styled.div)
>     in styled.div (at index.js:34)
>     in div (created by styled.div)
>     in styled.div (at index.js:33)
>     in div (created by styled.div)
>     in styled.div (at index.js:31)
>     in MainTemplate (at presenter.js:11)
>     in MainPagePresenter (created by Connect(MainPagePresenter))
>     in Connect(MainPagePresenter) (created by Route)
>     in Route (at index.js:20)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (at index.js:19)
>     in Provider (at index.js:18)
> 
> Consider adding an error boundary to your tree to customize error handling behavior.
> Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
> __stack_frame_overlay_proxy_console__ @ index.js:2178
> logCapturedError @ react-dom.development.js:14227
> logError @ react-dom.development.js:14266
> update.callback @ react-dom.development.js:14919
> callCallback @ react-dom.development.js:10879
> commitUpdateQueue @ react-dom.development.js:10923
> commitLifeCycles @ react-dom.development.js:14397
> commitAllLifeCycles @ react-dom.development.js:15463
> callCallback @ react-dom.development.js:100
> invokeGuardedCallbackDev @ react-dom.development.js:138
> invokeGuardedCallback @ react-dom.development.js:187
> commitRoot @ react-dom.development.js:15604
> completeRoot @ react-dom.development.js:16619
> performWorkOnRoot @ react-dom.development.js:16564
> performWork @ react-dom.development.js:16483
> performSyncWork @ react-dom.development.js:16455
> requestWork @ react-dom.development.js:16355
> scheduleWork$1 @ react-dom.development.js:16219
> enqueueSetState @ react-dom.development.js:11300
> ./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:270
> onStateChange @ connectAdvanced.js:205
> dispatch @ redux.js:221
> dispatch @ VM345:1
> (anonymous) @ middleware.js:66
> dispatch @ redux.js:563
> (anonymous) @ utils.js:250
> (anonymous) @ proc.js:489
> exec @ scheduler.js:19
> flush @ scheduler.js:60
> asap @ scheduler.js:33
> runPutEffect @ proc.js:486
> runEffect @ proc.js:435
> next @ proc.js:315
> currCb @ proc.js:388
> Promise.then (async)
> resolvePromise @ proc.js:450
> runCallEffect @ proc.js:517
> runEffect @ proc.js:435
> next @ proc.js:315
> currCb @ proc.js:388
> (anonymous) @ proc.js:499
> exec @ scheduler.js:19
> flush @ scheduler.js:60
> asap @ scheduler.js:33
> (anonymous) @ channel.js:185
> emit @ channel.js:26
> (anonymous) @ middleware.js:67
> dispatch @ VM345:1
> onLoadAggregation @ index.js:53
> Table._this._viewGraph @ index.js:136
> onClick @ index.js:60
> callCallback @ react-dom.development.js:100
> invokeGuardedCallbackDev @ react-dom.development.js:138
> invokeGuardedCallback @ react-dom.development.js:187
> invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
> executeDispatch @ react-dom.development.js:461
> executeDispatchesInOrder @ react-dom.development.js:480
> executeDispatchesAndRelease @ react-dom.development.js:581
> executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
> forEachAccumulated @ react-dom.development.js:562
> runEventsInBatch @ react-dom.development.js:723
> runExtractedEventsInBatch @ react-dom.development.js:732
> handleTopLevel @ react-dom.development.js:4477
> batchedUpdates$1 @ react-dom.development.js:16660
> batchedUpdates @ react-dom.development.js:2131
> dispatchEvent @ react-dom.development.js:4556
> interactiveUpdates$1 @ react-dom.development.js:16715
> interactiveUpdates @ react-dom.development.js:2150
> dispatchInteractiveEvent @ react-dom.development.js:4533
> index.js:2178 uncaught at aggregationLoad TypeError: Cannot read property 'prototype' of undefined
>     at isSeriesChild (http://localhost:3000/static/js/bundle.js:208094:30)
>     at http://localhost:3000/static/js/bundle.js:208106:21
>     at Array.filter (<anonymous>)
>     at getSeriesChildren (http://localhost:3000/static/js/bundle.js:208105:83)
>     at new XYPlot (http://localhost:3000/static/js/bundle.js:204187:106)
>     at constructClassInstance (http://localhost:3000/static/js/bundle.js:174674:18)
>     at updateClassComponent (http://localhost:3000/static/js/bundle.js:176371:7)
>     at beginWork (http://localhost:3000/static/js/bundle.js:177051:14)
>     at performUnitOfWork (http://localhost:3000/static/js/bundle.js:179090:12)
>     at workLoop (http://localhost:3000/static/js/bundle.js:179129:24)
>     at renderRoot (http://localhost:3000/static/js/bundle.js:179169:7)
>     at performWorkOnRoot (http://localhost:3000/static/js/bundle.js:179787:22)
>     at performWork (http://localhost:3000/static/js/bundle.js:179709:7)
>     at performSyncWork (http://localhost:3000/static/js/bundle.js:179681:3)
>     at requestWork (http://localhost:3000/static/js/bundle.js:179581:5)
>     at scheduleWork$1 (http://localhost:3000/static/js/bundle.js:179445:11)
>     at Object.enqueueSetState (http://localhost:3000/static/js/bundle.js:174526:5)
>     at Connect../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/bundle.js:208590:16)
>     at Connect.onStateChange (http://localhost:3000/static/js/bundle.js:189056:16)
>     at Object.dispatch (http://localhost:3000/static/js/bundle.js:212443:7)
>     at dispatch (<anonymous>:1:38223)
>     at http://localhost:3000/static/js/bundle.js:210640:22
>     at dispatch (http://localhost:3000/static/js/bundle.js:212785:28)
>     at http://localhost:3000/static/js/bundle.js:212144:12
>     at http://localhost:3000/static/js/bundle.js:211167:52
>     at exec (http://localhost:3000/static/js/bundle.js:211807:5)
>     at flush (http://localhost:3000/static/js/bundle.js:211848:5)
>     at asap (http://localhost:3000/static/js/bundle.js:211821:5)
>     at runPutEffect (http://localhost:3000/static/js/bundle.js:211164:69)
>     at runEffect (http://localhost:3000/static/js/bundle.js:211113:307)
>     at next (http://localhost:3000/static/js/bundle.js:210993:9)
>     at currCb (http://localhost:3000/static/js/bundle.js:211066:7)
> __stack_frame_overlay_proxy_console__ @ index.js:2178
> log @ utils.js:225
> logError @ proc.js:210
> (anonymous) @ proc.js:493
> exec @ scheduler.js:19
> flush @ scheduler.js:60
> asap @ scheduler.js:33
> runPutEffect @ proc.js:486
> runEffect @ proc.js:435
> next @ proc.js:315
> currCb @ proc.js:388
> Promise.then (async)
> resolvePromise @ proc.js:450
> runCallEffect @ proc.js:517
> runEffect @ proc.js:435
> next @ proc.js:315
> currCb @ proc.js:388
> (anonymous) @ proc.js:499
> exec @ scheduler.js:19
> flush @ scheduler.js:60
> asap @ scheduler.js:33
> (anonymous) @ channel.js:185
> emit @ channel.js:26
> (anonymous) @ middleware.js:67
> dispatch @ VM345:1
> onLoadAggregation @ index.js:53
> Table._this._viewGraph @ index.js:136
> onClick @ index.js:60
> callCallback @ react-dom.development.js:100
> invokeGuardedCallbackDev @ react-dom.development.js:138
> invokeGuardedCallback @ react-dom.development.js:187
> invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
> executeDispatch @ react-dom.development.js:461
> executeDispatchesInOrder @ react-dom.development.js:480
> executeDispatchesAndRelease @ react-dom.development.js:581
> executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
> forEachAccumulated @ react-dom.development.js:562
> runEventsInBatch @ react-dom.development.js:723
> runExtractedEventsInBatch @ react-dom.development.js:732
> handleTopLevel @ react-dom.development.js:4477
> batchedUpdates$1 @ react-dom.development.js:16660
> batchedUpdates @ react-dom.development.js:2131
> dispatchEvent @ react-dom.development.js:4556
> interactiveUpdates$1 @ react-dom.development.js:16715
> interactiveUpdates @ react-dom.development.js:2150
> dispatchInteractiveEvent @ react-dom.development.js:4533
> VM341:1 GET http://localhost:3000/%3Canonymous%3E 404 (Not Found)

**Comment by mcnuttandrew** [comment]
Maybe try using a VerticalRectSeriesCanvas ? If that doesn't work could you throw this into a codepen? I don't want to mis-diagnose your problem

**Comment by thinhly197** [comment]
I tried with VerticalRectSeriesCanvas, and the crosshair for tooltip cannot work...

**Comment by mcnuttandrew** [comment]
You could add a ghost series over that or a voronoi or something? Would you mind opening a code pen i'm interested to see what data is causing that error

**Comment by BertCh** [comment]
https://codesandbox.io/s/serene-wildflower-snyhx?fontsize=14

I am running into a similar issue with `MarkSeries`
